### ISSUE TITLE
add support for podman/containerd

### ISSUE THREAD

**Issue by k2s** [ruoshan/autoportforward#5]
Please add command line argument to extend your tool for other container runtimes.

It is probably easy to add [Podman](https://podman.io/) support. It has compatible command line for `cp`/`exec` commands.

[Containerd](https://containerd.io/) doesn't have `cp` command, but it looks for k8s you do same as described here https://github.com/containerd/containerd/issues/2044.

**Comment by ruoshan** [comment]
@k2s podman support done.

I took a look the the `ctr` cli of the containerd, looks like it's created for debug purpose as stated in the `ctr`'s usage output. So I'm going to table the `ctr` part for now.
