### ISSUE TITLE
apf exits after startup

### ISSUE THREAD

**Issue by warmingking** [ruoshan/autoportforward#9]
if container use some common port which already used in the host node, such as ssh(22), http(80)
the apf-agent may panic
![image](https://user-images.githubusercontent.com/14056172/148764238-f7c3bbc5-7883-4df7-b050-a617372ced4e.png)

**Comment by warmingking** [comment]
sorry for the confusing post, i try to debug according to this suggestion, https://github.com/ruoshan/autoportforward/issues/7#issuecomment-1006198520

the garbage characters in my screenshot seem that the apf-agent in container running ok? 
> "see if you can manually run it. let me known if it runs, prints some garbage characters and exits."

The problem I'm having is that apf automatically exits after it starts, instead of running continuously
![image](https://user-images.githubusercontent.com/14056172/148873592-b5881ffa-1d80-45be-85cc-5f0d2553171e.png)

**Comment by warmingking** [comment]
> Can you clarify the issue a little bit?
> 
> the `apf-agent` is not supposed to be run directly by the user, please use `apf` instead. that panic is always expected if apf-agent is run directly.
> 
> and I did add the logic to deal with ports under 1024, also when the listener fails to bind a socket to a specific port, a random port is chosen.

it seems the port number is not the reason for my problem
my title is not rigorous, I will edit it if the root cause is located

**Comment by ruoshan** [comment]
> sorry for the confusing post, I try to debug according to this suggestion, https://github.com/ruoshan/autoportforward/issues/7#issuecomment-1006198520
> 
> 
> 
> the garbage characters in my screenshot seem that the `apf-agent` in the container running ok? 
> 
> > "see if you can manually run it. let me know if it runs, prints some garbage characters, and exits."
> 
> 
> 
> The problem I'm having is that `apf` automatically exits after it starts, instead of running continuously
> 
> ![image](https://user-images.githubusercontent.com/14056172/148873592-b5881ffa-1d80-45be-85cc-5f0d2553171e.png)
> 
> 
> 
> 
> 
> 

Weird. it exited right away? is your docker server running on a remote host? my wild guess is something terminates the docker exec command, apf uses that cmd under the hood.

**Comment by warmingking** [comment]
> is your docker server running on a remote host?

no

> something terminates the docker exec command

may not, its something about this specific container ( I build base ubuntu:xenial  ), if I use another container ( [httpd](https://hub.docker.com/_/httpd) ), `apf` will run fine

**Comment by ruoshan** [comment]
I just pulled that image and install the `netcat-openbsd` pkg to play around (`nc -l 20990`). didn't encounter any issues so far. don't know how to reproduce this issue, I need to add more debug logs.

**Comment by ruoshan** [comment]
@warmingking hey, I just tag a new release 0.0.7. appreciate if you could try it with the `-d` on and post the logs both from local host and container here.

**Comment by warmingking** [comment]
> @warmingking hey, I just tag a new release 0.0.7. appreciate if you could try it with the `-d` on and post the logs both from local host and container here.

thanks for your work, I try the 0.0.7, but it also exit like before, there are log in host and container

The time is inconsistent because I don't have timezone mounted in container

```
# host log
2022/01/13 19:02:04 apf.go:79: Bootstraping
2022/01/13 19:02:05 apf.go:111: Creating pipe mux server
2022/01/13 19:02:05 apf.go:119: Starting manager
2022/01/13 19:02:05 apf.go:130: Starting proxy listener
2022/01/13 19:02:05 apf.go:143: Starting proxy forwarder
2022/01/13 19:02:05 apf.go:150: Waiting
2022/01/13 19:02:05 listener.go:49: New listener: 37713
2022/01/13 19:02:05 listener.go:49: New listener: 10022
2022/01/13 19:02:05 listener.go:49: New listener: 20990
2022/01/13 19:02:05 listener.go:49: New listener: 20991
2022/01/13 19:02:05 forwarder.go:39: Failed to accept new stream: EOF
2022/01/13 19:02:05 manager.go:88: Read EOF
2022/01/13 19:02:05 manager.go:264: Shutting down
2022/01/13 19:02:05 manager.go:81: Stop receiving
2022/01/13 19:02:05 manager.go:140: Stop sending
2022/01/13 19:02:05 apf.go:152: Byebye
 
# container log
2022/01/13 11:02:05 agent.go:24: Agent starts
2022/01/13 11:02:05 agent.go:37: Starting proxy listener
2022/01/13 11:02:05 agent.go:62: Starting proxy forwarder
2022/01/13 11:02:05 agent.go:68: Waiting
2022/01/13 11:02:05 agent.go:47: Starting portscanner
```

**Comment by ruoshan** [comment]
weird. why EOF so fast? I really think the culprit is something that kills the docker exec command under the hood. this is tricky, I didn't manage to reproduce it on my side.

**Comment by warmingking** [comment]
I think there are something about `GRPC`, if I start my `GRPC` server ( writo with `C++` ), `apf` would `EOF` fast, if I stop the `GRPC` server, `apf` run pretty well

**Comment by ruoshan** [comment]
> The problem lies in my application, my grpc server startup is a bit abnormal, if I stop my server, `apf` will work fine
> 
> 
> 
> Next, I will check the specific problem in my code

okay. shall I close this issue?

**Comment by warmingking** [comment]
> > The problem lies in my application, my grpc server startup is a bit abnormal, if I stop my server, `apf` will work fine
> > Next, I will check the specific problem in my code
> 
> okay. shall I close this issue?

Ok. Thanks very much
